import type { BonusCard, SpeciesCard } from "./types";

export const speciesCards: Record<string, SpeciesCard> = {
  acornWoodpecker: {
    id: "acornWoodpecker",
    name: "Carpintero Bellotero",
    scientificName: "Melanerpes formicivorus",
    habitats: ["forest"],
    cost: { seed: 3 },
    points: 5,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 46,
    powers: [
      {
        id: "acornWoodpecker.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  americanAvocet: {
    id: "americanAvocet",
    name: "Avoceta Americana",
    scientificName: "Recurvirostra americana",
    habitats: ["wetland"],
    cost: { insect: 2, seed: 1 },
    points: 6,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 79,
    powers: [
      {
        id: "americanAvocet.power1",
        timing: "onceBetweenTurns",
        kind: "layEgg",
        amount: 1,
        target: "nestType",
        nestType: "ground",
      },
    ],
  },
  americanBittern: {
    id: "americanBittern",
    name: "Avetoro Lentiginoso",
    scientificName: "Botaurus lentiginosus",
    habitats: ["wetland"],
    cost: { insect: 1, fish: 1, rodent: 1 },
    points: 7,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 107,
    powers: [
      {
        id: "americanBittern.power1",
        timing: "onActivate",
        kind: "fewestBirdsBenefit",
        habitat: "wetland",
        benefitType: "drawCard",
        amount: 1,
      },
    ],
  },
  americanCoot: {
    id: "americanCoot",
    name: "Focha Americana",
    scientificName: "Fulica americana",
    habitats: ["wetland"],
    cost: { seed: 1, wild: 1 },
    points: 3,
    eggCapacity: 5,
    nestType: "platform",
    wingspanCm: 61,
    powers: [
      {
        id: "americanCoot.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  americanCrow: {
    id: "americanCrow",
    name: "Cuervo Americano",
    scientificName: "Corvus brachyrhynchos",
    habitats: ["forest", "grassland", "wetland"],
    cost: { wild: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 99,
    powers: [
      {
        id: "americanCrow.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "wild",
        amount: 1,
        costsEgg: true,
        costEggExcludesSelf: true,
      },
    ],
  },
  americanGoldfinch: {
    id: "americanGoldfinch",
    name: "Jilguero Americano",
    scientificName: "Spinus tristis",
    habitats: ["grassland"],
    cost: { seed: 2 },
    points: 3,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "americanGoldfinch.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "seed",
        amount: 3,
      },
    ],
  },
  americanKestrel: {
    id: "americanKestrel",
    name: "Cernícalo Americano",
    scientificName: "Falco sparverius",
    habitats: ["grassland"],
    cost: { insect: 1, rodent: 1 },
    points: 5,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 56,
    powers: [
      {
        id: "americanKestrel.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  americanOystercatcher: {
    id: "americanOystercatcher",
    name: "Ostrero Americano",
    scientificName: "Haemotopus palliatus",
    habitats: ["wetland"],
    cost: { insect: 2 },
    points: 5,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 81,
    powers: [
      {
        id: "americanOystercatcher.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
      },
    ],
  },
  americanRobin: {
    id: "americanRobin",
    name: "Mirlo Primavera",
    scientificName: "Turdus migratorius",
    habitats: ["forest", "grassland"],
    cost: {},
    costAnyOf: ["insect", "fruit"],
    points: 1,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 43,
    powers: [
      {
        id: "americanRobin.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  americanWhitePelican: {
    id: "americanWhitePelican",
    name: "Pelícano Blanco Americano",
    scientificName: "Pelecanus erythrorhynchos",
    habitats: ["wetland"],
    cost: { fish: 2 },
    points: 5,
    eggCapacity: 1,
    nestType: "ground",
    wingspanCm: 274,
    powers: [
      {
        id: "americanWhitePelican.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 2,
        source: "deck",
        costResource: "fish",
        costAmount: 1,
      },
    ],
  },
  americanWoodcock: {
    id: "americanWoodcock",
    name: "Chocha Americana",
    scientificName: "Scolopax minor",
    habitats: ["forest", "grassland"],
    cost: { insect: 2, seed: 1 },
    points: 9,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 46,
    powers: [],
  },
  anhinga: {
    id: "anhinga",
    name: "Aninga",
    scientificName: "Anhinga anhinga",
    habitats: ["wetland"],
    cost: { fish: 2 },
    points: 6,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 114,
    powers: [
      {
        id: "anhinga.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  annasHummingbird: {
    id: "annasHummingbird",
    name: "Colibrí de Anna",
    scientificName: "Calypte anna",
    habitats: ["forest", "grassland", "wetland"],
    cost: { wild: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 13,
    powers: [
      {
        id: "annasHummingbird.power1",
        timing: "onActivate",
        kind: "allPlayersGainDie",
      },
    ],
  },
  ashThroatedFlycatcher: {
    id: "ashThroatedFlycatcher",
    name: "Copetón Cenizo",
    scientificName: "Myiarchus cinerascens",
    habitats: ["grassland"],
    cost: { insect: 2, fruit: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 30,
    powers: [
      {
        id: "ashThroatedFlycatcher.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "eachNestType",
        nestType: "cavity",
      },
    ],
  },
  atlanticPuffin: {
    id: "atlanticPuffin",
    name: "Frailecillo Atlántico",
    scientificName: "Fratercula arctica",
    habitats: ["wetland"],
    cost: { fish: 3 },
    points: 8,
    eggCapacity: 1,
    nestType: "wild",
    wingspanCm: 53,
    powers: [
      {
        id: "atlanticPuffin.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  bairdsSparrow: {
    id: "bairdsSparrow",
    name: "Chingolo de Baird",
    scientificName: "Ammodramus bairdii",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 23,
    powers: [
      {
        id: "bairdsSparrow.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "any",
      },
    ],
  },
  baldEagle: {
    id: "baldEagle",
    name: "Águila Calva",
    scientificName: "Haliaeetus leucocephalus",
    habitats: ["wetland"],
    cost: { fish: 2, rodent: 1 },
    points: 9,
    eggCapacity: 1,
    nestType: "platform",
    wingspanCm: 203,
    powers: [
      {
        id: "baldEagle.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "fish",
        amount: 1,
        from: "feeder",
        gainAllMatching: true,
      },
    ],
  },
  baltimoreOriole: {
    id: "baltimoreOriole",
    name: "Turpial de Baltimore",
    scientificName: "Icterus galbula",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 2 },
    points: 9,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 30,
    powers: [
      {
        id: "baltimoreOriole.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "fruit",
        benefitType: "resource",
      },
    ],
  },
  barnOwl: {
    id: "barnOwl",
    name: "Lechuza Común",
    scientificName: "Tyto alba",
    habitats: ["forest", "grassland", "wetland"],
    cost: { rodent: 2 },
    points: 5,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 107,
    powers: [
      {
        id: "barnOwl.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  barnSwallow: {
    id: "barnSwallow",
    name: "Golondrina Tijereta",
    scientificName: "Hirundo rustica",
    habitats: ["grassland", "wetland"],
    cost: { insect: 1 },
    points: 1,
    eggCapacity: 3,
    nestType: "wild",
    wingspanCm: 38,
    powers: [
      {
        id: "barnSwallow.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  barredOwl: {
    id: "barredOwl",
    name: "Búho Barrado",
    scientificName: "Strix varia",
    habitats: ["forest"],
    cost: { rodent: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 107,
    powers: [
      {
        id: "barredOwl.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  barrowsGoldeneye: {
    id: "barrowsGoldeneye",
    name: "Porrón de Barrow",
    scientificName: "Bucephala islandica",
    habitats: ["wetland"],
    cost: { insect: 1, seed: 1, fish: 1 },
    points: 5,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 71,
    powers: [
      {
        id: "barrowsGoldeneye.power1",
        timing: "onceBetweenTurns",
        kind: "layEgg",
        amount: 1,
        target: "nestType",
        nestType: "cavity",
      },
    ],
  },
  bellsVireo: {
    id: "bellsVireo",
    name: "Vireo de Bell",
    scientificName: "Vireo bellii",
    habitats: ["forest", "grassland"],
    cost: { insect: 2 },
    points: 4,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 18,
    powers: [
      {
        id: "bellsVireo.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  beltedKingfisher: {
    id: "beltedKingfisher",
    name: "Martín Pescador Norteamericano",
    scientificName: "Megaceryle alcyon",
    habitats: ["wetland"],
    cost: { fish: 1, wild: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "wild",
    wingspanCm: 53,
    powers: [
      {
        id: "beltedKingfisher.power1",
        timing: "onceBetweenTurns",
        kind: "gainResource",
        resource: "fish",
        amount: 1,
        habitat: "wetland",
      },
    ],
  },
  bewicksWren: {
    id: "bewicksWren",
    name: "Chivirín de Bewick",
    scientificName: "Thryomanes bewickii",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 2, seed: 1 },
    points: 4,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 18,
    powers: [
      {
        id: "bewicksWren.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  blackSkimmer: {
    id: "blackSkimmer",
    name: "Rayador Americano",
    scientificName: "Rynchops niger",
    habitats: ["wetland"],
    cost: { fish: 2 },
    points: 6,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 112,
    powers: [
      {
        id: "blackSkimmer.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  blackTern: {
    id: "blackTern",
    name: "Fumarel Negro",
    scientificName: "Chlidonias niger",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 4,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 61,
    powers: [
      {
        id: "blackTern.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
        thenDiscard: true,
      },
    ],
  },
  blackVulture: {
    id: "blackVulture",
    name: "Zopilote Negro",
    scientificName: "Coragyps atratus",
    habitats: ["forest"],
    cost: {},
    points: 2,
    eggCapacity: 1,
    nestType: "cavity",
    wingspanCm: 150,
    powers: [
      {
        id: "blackVulture.power1",
        timing: "onceBetweenTurns",
        kind: "gainResource",
        amount: 1,
        from: "feeder",
        anyDie: true,
      },
    ],
  },
  blackBelliedWhistlingDuck: {
    id: "blackBelliedWhistlingDuck",
    name: "Pijije Aliblanco",
    scientificName: "Dendrocygna autumnalis",
    habitats: ["wetland"],
    cost: { seed: 2 },
    points: 2,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 76,
    powers: [
      {
        id: "blackBelliedWhistlingDuck.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 2,
        source: "deck",
        costResource: "seed",
        costAmount: 1,
      },
    ],
  },
  blackBilledMagpie: {
    id: "blackBilledMagpie",
    name: "Urraca Norteamericana",
    scientificName: "Pica hudsonia",
    habitats: ["grassland"],
    cost: { wild: 2 },
    points: 3,
    eggCapacity: 3,
    nestType: "wild",
    wingspanCm: 64,
    powers: [
      {
        id: "blackBilledMagpie.power1",
        timing: "onceBetweenTurns",
        kind: "gainResource",
        amount: 1,
        from: "feeder",
        anyDie: true,
      },
    ],
  },
  blackCrownedNightHeron: {
    id: "blackCrownedNightHeron",
    name: "Garza Nocturna Coroninegra",
    scientificName: "Nycticorax nycticorax",
    habitats: ["wetland"],
    cost: { insect: 1, fish: 1, rodent: 1 },
    points: 9,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 112,
    powers: [
      {
        id: "blackCrownedNightHeron.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "wild",
        amount: 1,
        costsEgg: true,
        costEggExcludesSelf: true,
      },
    ],
  },
  blackNeckedStilt: {
    id: "blackNeckedStilt",
    name: "Candelero Americano",
    scientificName: "Himantopus mexicanus",
    habitats: ["wetland"],
    cost: { insect: 2 },
    points: 4,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 74,
    powers: [
      {
        id: "blackNeckedStilt.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
      },
    ],
  },
  blueGrosbeak: {
    id: "blueGrosbeak",
    name: "Picogrueso Azul",
    scientificName: "Passerina caerulea",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, seed: 2 },
    points: 4,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 28,
    powers: [
      {
        id: "blueGrosbeak.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  blueJay: {
    id: "blueJay",
    name: "Chara Azul",
    scientificName: "Cyanocitta cristata",
    habitats: ["forest"],
    cost: { seed: 1, wild: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 41,
    powers: [
      {
        id: "blueJay.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  blueGrayGnatcatcher: {
    id: "blueGrayGnatcatcher",
    name: "Perlita Grisilla",
    scientificName: "Polioptila caerulea",
    habitats: ["forest"],
    cost: { insect: 1 },
    points: 1,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 15,
    powers: [
      {
        id: "blueGrayGnatcatcher.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        amount: 1,
      },
    ],
  },
  blueWingedWarbler: {
    id: "blueWingedWarbler",
    name: "Reinita Alidorada",
    scientificName: "Vermivora cyanoptera",
    habitats: ["forest", "grassland"],
    cost: { insect: 2 },
    points: 8,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 20,
    powers: [],
  },
  bobolink: {
    id: "bobolink",
    name: "Charlatán",
    scientificName: "Dolichonyx oryzivorus",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 2 },
    points: 4,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 30,
    powers: [
      {
        id: "bobolink.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "eachNestType",
        nestType: "ground",
      },
    ],
  },
  brewersBlackbird: {
    id: "brewersBlackbird",
    name: "Tordo de Brewer",
    scientificName: "Euphagus cyanocephalus",
    habitats: ["grassland"],
    cost: { seed: 1, wild: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 41,
    powers: [
      {
        id: "brewersBlackbird.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  bronzedCowbird: {
    id: "bronzedCowbird",
    name: "Tordo Ojirrojo",
    scientificName: "Molothrus aeneus",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 5,
    eggCapacity: 0,
    wingspanCm: 36,
    powers: [
      {
        id: "bronzedCowbird.power1",
        timing: "onceBetweenTurns",
        kind: "layEgg",
        amount: 1,
        target: "nestType",
        nestType: "bowl",
      },
    ],
  },
  brownPelican: {
    id: "brownPelican",
    name: "Pelícano Pardo",
    scientificName: "Pelecanus occidentalis",
    habitats: ["wetland"],
    cost: { fish: 2 },
    points: 4,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 201,
    powers: [
      {
        id: "brownPelican.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "fish",
        amount: 3,
      },
    ],
  },
  brownHeadedCowbird: {
    id: "brownHeadedCowbird",
    name: "Tordo Cabecicafé",
    scientificName: "Molothrus ater",
    habitats: ["grassland"],
    cost: { seed: 1 },
    points: 3,
    eggCapacity: 0,
    wingspanCm: 30,
    powers: [
      {
        id: "brownHeadedCowbird.power1",
        timing: "onceBetweenTurns",
        kind: "layEgg",
        amount: 1,
        target: "nestType",
        nestType: "bowl",
      },
    ],
  },
  burrowingOwl: {
    id: "burrowingOwl",
    name: "Lechucita de las Vizcacheras",
    scientificName: "Athene cunicularia",
    habitats: ["grassland"],
    cost: { insect: 1, rodent: 1 },
    points: 5,
    eggCapacity: 4,
    nestType: "wild",
    wingspanCm: 53,
    powers: [
      {
        id: "burrowingOwl.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  bushtit: {
    id: "bushtit",
    name: "Sastrecillo Común",
    scientificName: "Psaltriparus minimus",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, seed: 1 },
    points: 2,
    eggCapacity: 5,
    nestType: "wild",
    wingspanCm: 15,
    powers: [
      {
        id: "bushtit.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  californiaCondor: {
    id: "californiaCondor",
    name: "Cóndor de California",
    scientificName: "Gymnogyps californianus",
    habitats: ["forest", "grassland", "wetland"],
    cost: {},
    points: 1,
    eggCapacity: 1,
    nestType: "ground",
    wingspanCm: 277,
    powers: [
      {
        id: "californiaCondor.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  californiaQuail: {
    id: "californiaQuail",
    name: "Codorniz de California",
    scientificName: "Callipepla californica",
    habitats: ["forest", "grassland"],
    cost: { insect: 1, seed: 2 },
    points: 3,
    eggCapacity: 6,
    nestType: "ground",
    wingspanCm: 36,
    powers: [
      {
        id: "californiaQuail.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  canadaGoose: {
    id: "canadaGoose",
    name: "Ganso Canadiense",
    scientificName: "Branta canadensis",
    habitats: ["grassland", "wetland"],
    cost: { seed: 2 },
    points: 3,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 132,
    powers: [
      {
        id: "canadaGoose.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 2,
        source: "deck",
        costResource: "seed",
        costAmount: 1,
      },
    ],
  },
  carolinaChickadee: {
    id: "carolinaChickadee",
    name: "Carbonero de Carolina",
    scientificName: "Poecile carolinensis",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 20,
    powers: [
      {
        id: "carolinaChickadee.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  carolinaWren: {
    id: "carolinaWren",
    name: "Chivirín de Carolina",
    scientificName: "Thryothorus ludovicianus",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "fruit"],
    points: 1,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 20,
    powers: [
      {
        id: "carolinaWren.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
      },
    ],
  },
  cassinsFinch: {
    id: "cassinsFinch",
    name: "Camachuelo de Cassin",
    scientificName: "Haemorhous cassinii",
    habitats: ["forest"],
    cost: { seed: 1, fruit: 1 },
    points: 4,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 30,
    powers: [
      {
        id: "cassinsFinch.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  cassinsSparrow: {
    id: "cassinsSparrow",
    name: "Gorrión de Cassin",
    scientificName: "Peucaea cassinii",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 20,
    powers: [
      {
        id: "cassinsSparrow.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "any",
      },
    ],
  },
  cedarWaxwing: {
    id: "cedarWaxwing",
    name: "Ampelis Chinito",
    scientificName: "Bombycilla cedrorum",
    habitats: ["forest", "grassland"],
    cost: { fruit: 2 },
    points: 3,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 25,
    powers: [
      {
        id: "cedarWaxwing.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainResource: "fruit",
      },
    ],
  },
  ceruleanWarbler: {
    id: "ceruleanWarbler",
    name: "Reinita Cerúlea",
    scientificName: "Setophaga cerulea",
    habitats: ["forest"],
    cost: { insect: 1, seed: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 20,
    powers: [
      {
        id: "ceruleanWarbler.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  chestnutCollaredLongspur: {
    id: "chestnutCollaredLongspur",
    name: "Escribano Collarejo",
    scientificName: "Calcarius ornatus",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 2 },
    points: 5,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 25,
    powers: [
      {
        id: "chestnutCollaredLongspur.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  chihuahuanRaven: {
    id: "chihuahuanRaven",
    name: "Cuervo Llanero",
    scientificName: "Corvus cryptoleucus",
    habitats: ["grassland"],
    cost: { rodent: 1, wild: 2 },
    points: 4,
    eggCapacity: 3,
    nestType: "platform",
    wingspanCm: 112,
    powers: [
      {
        id: "chihuahuanRaven.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "wild",
        amount: 2,
        costsEgg: true,
        costEggExcludesSelf: true,
      },
    ],
  },
  chimneySwift: {
    id: "chimneySwift",
    name: "Vencejo de Chimenea",
    scientificName: "Chaetura pelagica",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 2 },
    points: 3,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 36,
    powers: [
      {
        id: "chimneySwift.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  chippingSparrow: {
    id: "chippingSparrow",
    name: "Chingolo Cejicastaño",
    scientificName: "Spizella passerina",
    habitats: ["forest", "grassland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 1,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "chippingSparrow.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "any",
      },
    ],
  },
  clarksGrebe: {
    id: "clarksGrebe",
    name: "Achichilique de Clark",
    scientificName: "Aechmophorus clarkii",
    habitats: ["wetland"],
    cost: { fish: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 61,
    powers: [
      {
        id: "clarksGrebe.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
        thenDiscard: true,
      },
    ],
  },
  clarksNutcracker: {
    id: "clarksNutcracker",
    name: "Cascanueces Americano",
    scientificName: "Nucifraga columbiana",
    habitats: ["forest"],
    cost: { seed: 2, wild: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 61,
    powers: [
      {
        id: "clarksNutcracker.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  commonGrackle: {
    id: "commonGrackle",
    name: "Zanate Común",
    scientificName: "Quiscalus quiscula",
    habitats: ["forest", "grassland", "wetland"],
    cost: { seed: 1, wild: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 43,
    powers: [
      {
        id: "commonGrackle.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  commonLoon: {
    id: "commonLoon",
    name: "Colimbo Grande",
    scientificName: "Gavia immer",
    habitats: ["wetland"],
    cost: { fish: 1, wild: 1 },
    points: 6,
    eggCapacity: 1,
    nestType: "ground",
    wingspanCm: 117,
    powers: [
      {
        id: "commonLoon.power1",
        timing: "onActivate",
        kind: "fewestBirdsBenefit",
        habitat: "wetland",
        benefitType: "drawCard",
        amount: 1,
      },
    ],
  },
  commonMerganser: {
    id: "commonMerganser",
    name: "Mergo Mayor",
    scientificName: "Mergus merganser",
    habitats: ["wetland"],
    cost: { fish: 1, wild: 1 },
    points: 5,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 86,
    powers: [
      {
        id: "commonMerganser.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  commonNighthawk: {
    id: "commonNighthawk",
    name: "Añapero Zumbón",
    scientificName: "Chordeiles minor",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 2 },
    points: 3,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 56,
    powers: [
      {
        id: "commonNighthawk.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  commonRaven: {
    id: "commonRaven",
    name: "Cuervo Grande",
    scientificName: "Corvus corax",
    habitats: ["forest", "grassland", "wetland"],
    cost: { rodent: 1, wild: 2 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 135,
    powers: [
      {
        id: "commonRaven.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "wild",
        amount: 2,
        costsEgg: true,
        costEggExcludesSelf: true,
      },
    ],
  },
  commonYellowthroat: {
    id: "commonYellowthroat",
    name: "Antifacito Común",
    scientificName: "Geothylypis trichas",
    habitats: ["wetland"],
    cost: { insect: 1 },
    points: 1,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 18,
    powers: [
      {
        id: "commonYellowthroat.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        thenDiscard: true,
      },
    ],
  },
  coopersHawk: {
    id: "coopersHawk",
    name: "Gavilán de Cooper",
    scientificName: "Accipiter cooperii",
    habitats: ["forest"],
    cost: { rodent: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 79,
    powers: [
      {
        id: "coopersHawk.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  darkEyedJunco: {
    id: "darkEyedJunco",
    name: "Junco Ojioscuro",
    scientificName: "Junco hyemalis",
    habitats: ["forest", "grassland"],
    cost: { insect: 1, seed: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 23,
    powers: [
      {
        id: "darkEyedJunco.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainResource: "seed",
      },
    ],
  },
  dickcissel: {
    id: "dickcissel",
    name: "Arrocero Americano",
    scientificName: "Spiza americana",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 2 },
    points: 4,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 25,
    powers: [
      {
        id: "dickcissel.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  doubleCrestedCormorant: {
    id: "doubleCrestedCormorant",
    name: "Cormorán Bicrestado",
    scientificName: "Phalacrocorax auritus",
    habitats: ["wetland"],
    cost: { fish: 1, wild: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "platform",
    wingspanCm: 132,
    powers: [
      {
        id: "doubleCrestedCormorant.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 2,
        source: "deck",
        costResource: "fish",
        costAmount: 1,
      },
    ],
  },
  downyWoodpecker: {
    id: "downyWoodpecker",
    name: "Carpintero Velloso Menor",
    scientificName: "Picoides pubescens",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 3,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 30,
    powers: [
      {
        id: "downyWoodpecker.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["forest"],
      },
    ],
  },
  easternBluebird: {
    id: "easternBluebird",
    name: "Azulejo Gorjicanelo",
    scientificName: "Sialia sialis",
    habitats: ["grassland"],
    cost: { insect: 1, fruit: 1 },
    points: 4,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 33,
    powers: [
      {
        id: "easternBluebird.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["grassland"],
      },
    ],
  },
  easternKingbird: {
    id: "easternKingbird",
    name: "Tirano Oriental",
    scientificName: "Tyrannus tyrannus",
    habitats: ["forest", "grassland", "wetland"],
    cost: {},
    costAnyOf: ["insect", "fruit"],
    points: 2,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 38,
    powers: [
      {
        id: "easternKingbird.power1",
        timing: "onceBetweenTurns",
        kind: "gainResource",
        resource: "insect",
        amount: 1,
        habitat: "forest",
      },
    ],
  },
  easternPhoebe: {
    id: "easternPhoebe",
    name: "Mosquero Fibí",
    scientificName: "Sayornis phoebe",
    habitats: ["forest", "grassland", "wetland"],
    cost: {},
    costAnyOf: ["insect", "fruit"],
    points: 3,
    eggCapacity: 4,
    nestType: "wild",
    wingspanCm: 28,
    powers: [
      {
        id: "easternPhoebe.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "insect",
        benefitType: "resource",
      },
    ],
  },
  easternScreechOwl: {
    id: "easternScreechOwl",
    name: "Tecolote Oriental",
    scientificName: "Megascops asio",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "rodent"],
    points: 4,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 51,
    powers: [
      {
        id: "easternScreechOwl.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  ferruginousHawk: {
    id: "ferruginousHawk",
    name: "Aguililla Herrumbrosa",
    scientificName: "Buteo regalis",
    habitats: ["grassland"],
    cost: { rodent: 2 },
    points: 6,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 142,
    powers: [
      {
        id: "ferruginousHawk.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  fishCrow: {
    id: "fishCrow",
    name: "Cuervo Pescador",
    scientificName: "Corvus ossifragus",
    habitats: ["forest", "grassland", "wetland"],
    cost: { fish: 1, wild: 1 },
    points: 6,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 91,
    powers: [
      {
        id: "fishCrow.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "wild",
        amount: 1,
        costsEgg: true,
        costEggExcludesSelf: true,
      },
    ],
  },
  forstersTern: {
    id: "forstersTern",
    name: "Charrán de Forster",
    scientificName: "Sterna forsteri",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 4,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 79,
    powers: [
      {
        id: "forstersTern.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
        thenDiscard: true,
      },
    ],
  },
  franklinsGull: {
    id: "franklinsGull",
    name: "Gaviota de Franklin",
    scientificName: "Leucophaeus pipixcan",
    habitats: ["grassland", "wetland"],
    cost: { fish: 1, wild: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 91,
    powers: [
      {
        id: "franklinsGull.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        costsEgg: true,
      },
    ],
  },
  goldenEagle: {
    id: "goldenEagle",
    name: "Águila Real",
    scientificName: "Aquila chrysaetos",
    habitats: ["grassland", "wetland"],
    cost: { rodent: 3 },
    points: 8,
    eggCapacity: 1,
    nestType: "platform",
    wingspanCm: 201,
    powers: [
      {
        id: "goldenEagle.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 100,
      },
    ],
  },
  grasshopperSparrow: {
    id: "grasshopperSparrow",
    name: "Gorrión Chapulín",
    scientificName: "Ammodramus savannarum",
    habitats: ["grassland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 20,
    powers: [
      {
        id: "grasshopperSparrow.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "any",
      },
    ],
  },
  grayCatbird: {
    id: "grayCatbird",
    name: "Maullador Gris",
    scientificName: "Dumetella carolinensis",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, fruit: 2 },
    points: 5,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 28,
    powers: [
      {
        id: "grayCatbird.power1",
        timing: "onActivate",
        kind: "repeatPower",
      },
    ],
  },
  greatBlueHeron: {
    id: "greatBlueHeron",
    name: "Garza Azulada",
    scientificName: "Ardea herodias",
    habitats: ["wetland"],
    cost: { insect: 1, fish: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 183,
    powers: [
      {
        id: "greatBlueHeron.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["wetland"],
      },
    ],
  },
  greatCrestedFlycatcher: {
    id: "greatCrestedFlycatcher",
    name: "Copetón Viajero",
    scientificName: "Myiarchus crinitus",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 1 },
    points: 5,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 33,
    powers: [
      {
        id: "greatCrestedFlycatcher.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        amount: 1,
        from: "feeder",
      },
    ],
  },
  greatEgret: {
    id: "greatEgret",
    name: "Garza Blanca",
    scientificName: "Ardea alba",
    habitats: ["wetland"],
    cost: { fish: 2, rodent: 1 },
    points: 7,
    eggCapacity: 3,
    nestType: "platform",
    wingspanCm: 130,
    powers: [
      {
        id: "greatEgret.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["wetland"],
      },
    ],
  },
  greatHornedOwl: {
    id: "greatHornedOwl",
    name: "Búho Cornudo",
    scientificName: "Bubo virginianus",
    habitats: ["forest"],
    cost: { rodent: 3 },
    points: 8,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 112,
    powers: [
      {
        id: "greatHornedOwl.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 100,
      },
    ],
  },
  greaterPrairieChicken: {
    id: "greaterPrairieChicken",
    name: "Gallo de las Praderas Mayor",
    scientificName: "Tympanuchus cupido",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 2 },
    points: 5,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 71,
    powers: [
      {
        id: "greaterPrairieChicken.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  greaterRoadrunner: {
    id: "greaterRoadrunner",
    name: "Correcaminos Norteño",
    scientificName: "Geococcyx californianus",
    habitats: ["grassland"],
    cost: { insect: 1, rodent: 1, wild: 1 },
    points: 7,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 56,
    powers: [
      {
        id: "greaterRoadrunner.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 50,
      },
    ],
  },
  greenHeron: {
    id: "greenHeron",
    name: "Garcita Verde",
    scientificName: "Butorides virescens",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 4,
    eggCapacity: 3,
    nestType: "platform",
    wingspanCm: 66,
    powers: [
      {
        id: "greenHeron.power1",
        timing: "onActivate",
        kind: "tradeResource",
        costResource: "wild",
        gainResource: "fish",
        amount: 1,
      },
    ],
  },
  hermitThrush: {
    id: "hermitThrush",
    name: "Zorzalito Colirrufo",
    scientificName: "Catharus guttatus",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 2 },
    points: 7,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 30,
    powers: [
      {
        id: "hermitThrush.power1",
        timing: "onActivate",
        kind: "fewestBirdsBenefit",
        habitat: "forest",
        benefitType: "gainDieFromFeeder",
      },
    ],
  },
  hoodedMerganser: {
    id: "hoodedMerganser",
    name: "Mergo Copetón",
    scientificName: "Lophodytes cucullatus",
    habitats: ["wetland"],
    cost: { insect: 1, fish: 1 },
    points: 5,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 61,
    powers: [
      {
        id: "hoodedMerganser.power1",
        timing: "onActivate",
        kind: "repeatPower",
        predatorOnly: true,
      },
    ],
  },
  hoodedWarbler: {
    id: "hoodedWarbler",
    name: "Chipe de Capucha",
    scientificName: "Setophaga citrina",
    habitats: ["forest"],
    cost: { insect: 2 },
    points: 7,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 18,
    powers: [],
  },
  hornedLark: {
    id: "hornedLark",
    name: "Alondra Cornuda",
    scientificName: "Eremophila alpestris",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 5,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 30,
    powers: [
      {
        id: "hornedLark.power1",
        timing: "onceBetweenTurns",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        habitat: "grassland",
      },
    ],
  },
  houseFinch: {
    id: "houseFinch",
    name: "Pinzón Mexicano",
    scientificName: "Haemorhous mexicanus",
    habitats: ["forest", "grassland", "wetland"],
    cost: { seed: 1, fruit: 1 },
    points: 3,
    eggCapacity: 6,
    nestType: "bowl",
    wingspanCm: 25,
    powers: [
      {
        id: "houseFinch.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  houseWren: {
    id: "houseWren",
    name: "Chivirín Saltapared",
    scientificName: "Troglodytes aedon",
    habitats: ["forest", "grassland"],
    cost: { insect: 1 },
    points: 1,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 15,
    powers: [
      {
        id: "houseWren.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["grassland","forest"],
      },
    ],
  },
  incaDove: {
    id: "incaDove",
    name: "Tortolita Colilarga",
    scientificName: "Columbina inca",
    habitats: ["grassland"],
    cost: { seed: 2 },
    points: 2,
    eggCapacity: 4,
    nestType: "platform",
    wingspanCm: 28,
    powers: [
      {
        id: "incaDove.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "eachNestType",
        nestType: "platform",
      },
    ],
  },
  indigoBunting: {
    id: "indigoBunting",
    name: "Colorín Azul",
    scientificName: "Passerina cyanea",
    habitats: ["forest", "grassland"],
    cost: { insect: 1, seed: 1, fruit: 1 },
    points: 5,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 20,
    powers: [
      {
        id: "indigoBunting.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        resourceAlt: "fruit",
        amount: 1,
        from: "feeder",
      },
    ],
  },
  juniperTitmouse: {
    id: "juniperTitmouse",
    name: "Carbonero de los Enebros",
    scientificName: "Baeolophus ridgwayi",
    habitats: ["forest"],
    cost: { insect: 1, seed: 1 },
    points: 4,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 23,
    powers: [
      {
        id: "juniperTitmouse.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  killdeer: {
    id: "killdeer",
    name: "Chorlito Tildío",
    scientificName: "Charadrius vociferus",
    habitats: ["grassland", "wetland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 1,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 46,
    powers: [
      {
        id: "killdeer.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        costsEgg: true,
      },
    ],
  },
  kingRail: {
    id: "kingRail",
    name: "Rascón Real",
    scientificName: "Rallus elegans",
    habitats: ["wetland"],
    cost: { insect: 1, fish: 1, wild: 1 },
    points: 4,
    eggCapacity: 6,
    nestType: "platform",
    wingspanCm: 51,
    powers: [
      {
        id: "kingRail.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  lazuliBunting: {
    id: "lazuliBunting",
    name: "Colorín Lázuli",
    scientificName: "Passerina amoena",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1, fruit: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "lazuliBunting.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "allPlayersNestType",
        nestType: "bowl",
        activePlayerBonus: 1,
      },
    ],
  },
  lincolnsSparrow: {
    id: "lincolnsSparrow",
    name: "Chingolo de Lincoln",
    scientificName: "Melospiza lincolnii",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, seed: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 20,
    powers: [
      {
        id: "lincolnsSparrow.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  loggerheadShrike: {
    id: "loggerheadShrike",
    name: "Verdugo Americano",
    scientificName: "Lanius ludovicianus",
    habitats: ["grassland", "wetland"],
    cost: { insect: 1, rodent: 1 },
    points: 3,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 30,
    powers: [
      {
        id: "loggerheadShrike.power1",
        timing: "onceBetweenTurns",
        kind: "cacheFood",
        resource: "rodent",
        amount: 1,
        source: "supply",
      },
    ],
  },
  mallard: {
    id: "mallard",
    name: "Ánade Real",
    scientificName: "Anas platyrhynchos",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 0,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 89,
    powers: [
      {
        id: "mallard.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
      },
    ],
  },
  mississippiKite: {
    id: "mississippiKite",
    name: "Milano Migratorio",
    scientificName: "Ictinia mississippiensis",
    habitats: ["forest", "grassland"],
    cost: {},
    costAnyOf: ["insect", "rodent"],
    points: 4,
    eggCapacity: 1,
    nestType: "platform",
    wingspanCm: 79,
    powers: [
      {
        id: "mississippiKite.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "rodent",
      },
    ],
  },
  mountainBluebird: {
    id: "mountainBluebird",
    name: "Azulejo de Montaña",
    scientificName: "Sialia currucoides",
    habitats: ["grassland"],
    cost: { insect: 1, fruit: 1 },
    points: 4,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 36,
    powers: [
      {
        id: "mountainBluebird.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["grassland"],
      },
    ],
  },
  mountainChickadee: {
    id: "mountainChickadee",
    name: "Carbonero de las Montañas",
    scientificName: "Poecile gambeli",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 23,
    powers: [
      {
        id: "mountainChickadee.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  mourningDove: {
    id: "mourningDove",
    name: "Huilota Común",
    scientificName: "Zenaida macroura",
    habitats: ["forest", "grassland", "wetland"],
    cost: { seed: 1 },
    points: 0,
    eggCapacity: 5,
    nestType: "platform",
    wingspanCm: 46,
    powers: [
      {
        id: "mourningDove.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  northernBobwhite: {
    id: "northernBobwhite",
    name: "Codorniz Cotuí",
    scientificName: "Colinus virginianus",
    habitats: ["grassland"],
    cost: { seed: 3 },
    points: 5,
    eggCapacity: 6,
    nestType: "ground",
    wingspanCm: 33,
    powers: [
      {
        id: "northernBobwhite.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  northernCardinal: {
    id: "northernCardinal",
    name: "Cardenal Rojo",
    scientificName: "Cardinalis cardinalis",
    habitats: ["forest"],
    cost: { seed: 1, fruit: 1 },
    points: 3,
    eggCapacity: 5,
    nestType: "bowl",
    wingspanCm: 30,
    powers: [
      {
        id: "northernCardinal.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "fruit",
        amount: 1,
      },
    ],
  },
  northernFlicker: {
    id: "northernFlicker",
    name: "Carpintero Escapulario",
    scientificName: "Colaptes auratus",
    habitats: ["forest", "grassland"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 2,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 51,
    powers: [
      {
        id: "northernFlicker.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        amount: 1,
        from: "feeder",
        gainAllMatching: true,
      },
    ],
  },
  northernHarrier: {
    id: "northernHarrier",
    name: "Aguilucho Pálido",
    scientificName: "Circus cyaneus",
    habitats: ["grassland", "wetland"],
    cost: { rodent: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 109,
    powers: [
      {
        id: "northernHarrier.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  northernMockingbird: {
    id: "northernMockingbird",
    name: "Cenzontle Norteño",
    scientificName: "Mimus polyglottos",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, fruit: 1 },
    points: 2,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 36,
    powers: [
      {
        id: "northernMockingbird.power1",
        timing: "onActivate",
        kind: "repeatPower",
      },
    ],
  },
  northernShoveler: {
    id: "northernShoveler",
    name: "Pato Cuchara Norteño",
    scientificName: "Spatula clypeata",
    habitats: ["wetland"],
    cost: { insect: 1, seed: 2 },
    points: 7,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 76,
    powers: [
      {
        id: "northernShoveler.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        benefitType: "card",
      },
    ],
  },
  osprey: {
    id: "osprey",
    name: "Águila Pescadora",
    scientificName: "Pandion haliaetus",
    habitats: ["wetland"],
    cost: { fish: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 160,
    powers: [
      {
        id: "osprey.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "fish",
        benefitType: "resource",
      },
    ],
  },
  paintedBunting: {
    id: "paintedBunting",
    name: "Colorín Sietecolores",
    scientificName: "Passerina ciris",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 2 },
    points: 5,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "paintedBunting.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  peregrineFalcon: {
    id: "peregrineFalcon",
    name: "Halcón Peregrino",
    scientificName: "Falco peregrinus",
    habitats: ["grassland", "wetland"],
    cost: { rodent: 2 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 104,
    powers: [
      {
        id: "peregrineFalcon.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 100,
      },
    ],
  },
  piedBilledGrebe: {
    id: "piedBilledGrebe",
    name: "Zambullidor Piquipinto",
    scientificName: "Podilymbus podiceps",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 0,
    eggCapacity: 4,
    nestType: "platform",
    wingspanCm: 41,
    powers: [
      {
        id: "piedBilledGrebe.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        thenDiscard: true,
      },
    ],
  },
  pileatedWoodpecker: {
    id: "pileatedWoodpecker",
    name: "Carpintero Real",
    scientificName: "Dryocopus pileatus",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 74,
    powers: [
      {
        id: "pileatedWoodpecker.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "allPlayersNestType",
        nestType: "cavity",
        activePlayerBonus: 1,
      },
    ],
  },
  pineSiskin: {
    id: "pineSiskin",
    name: "Jilguero Pinero",
    scientificName: "Spinus pinus",
    habitats: ["forest"],
    cost: { seed: 2 },
    points: 3,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "pineSiskin.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainResource: "seed",
      },
    ],
  },
  prothonotaryWarbler: {
    id: "prothonotaryWarbler",
    name: "Chipe Protonotario",
    scientificName: "Protonotaria citrea",
    habitats: ["forest", "wetland"],
    cost: { insect: 2, seed: 1 },
    points: 8,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 23,
    powers: [],
  },
  purpleGallinule: {
    id: "purpleGallinule",
    name: "Gallineta Morada",
    scientificName: "Porphyrio martinicus",
    habitats: ["wetland"],
    cost: { seed: 1, fruit: 1, wild: 1 },
    points: 7,
    eggCapacity: 4,
    nestType: "platform",
    wingspanCm: 56,
    powers: [
      {
        id: "purpleGallinule.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        benefitType: "card",
      },
    ],
  },
  purpleMartin: {
    id: "purpleMartin",
    name: "Golondrina Purpúrea",
    scientificName: "Progne subis",
    habitats: ["grassland", "wetland"],
    cost: { insect: 1 },
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 46,
    powers: [
      {
        id: "purpleMartin.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  pygmyNuthatch: {
    id: "pygmyNuthatch",
    name: "Sita Enana",
    scientificName: "Sitta pygmaea",
    habitats: ["forest"],
    cost: { insect: 1, seed: 1 },
    points: 2,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 20,
    powers: [
      {
        id: "pygmyNuthatch.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainResource: "insect",
        thenGainResourceAlt: "seed",
      },
    ],
  },
  redCrossbill: {
    id: "redCrossbill",
    name: "Piquituerto Rojo",
    scientificName: "Loxia curvirostra",
    habitats: ["forest"],
    cost: { seed: 2 },
    points: 6,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 28,
    powers: [
      {
        id: "redCrossbill.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "seed",
        benefitType: "resource",
      },
    ],
  },
  redBelliedWoodpecker: {
    id: "redBelliedWoodpecker",
    name: "Carpintero Ventridorado",
    scientificName: "Melanerpes carolinus",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 1,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 41,
    powers: [
      {
        id: "redBelliedWoodpecker.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  redBreastedNuthatch: {
    id: "redBreastedNuthatch",
    name: "Sita Canadiense",
    scientificName: "Sitta canadensis",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 23,
    powers: [
      {
        id: "redBreastedNuthatch.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  redCockadedWoodpecker: {
    id: "redCockadedWoodpecker",
    name: "Carpintero de Cocarda Roja",
    scientificName: "Picoides borealis",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 36,
    powers: [
      {
        id: "redCockadedWoodpecker.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  redEyedVireo: {
    id: "redEyedVireo",
    name: "Vireo Ojirrojo",
    scientificName: "Vireo olivaceus",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "wild",
    wingspanCm: 25,
    powers: [
      {
        id: "redEyedVireo.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["forest"],
      },
    ],
  },
  redHeadedWoodpecker: {
    id: "redHeadedWoodpecker",
    name: "Carpintero Cabecirrojo",
    scientificName: "Melanerpes erythrocephalus",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, seed: 1, wild: 1 },
    points: 4,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 43,
    powers: [
      {
        id: "redHeadedWoodpecker.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  redShoulderedHawk: {
    id: "redShoulderedHawk",
    name: "Aguililla Alirrojiza",
    scientificName: "Buteo lineatus",
    habitats: ["forest"],
    cost: { rodent: 1 },
    points: 3,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 102,
    powers: [
      {
        id: "redShoulderedHawk.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  redTailedHawk: {
    id: "redTailedHawk",
    name: "Aguililla Colirroja",
    scientificName: "Buteo jamaicensis",
    habitats: ["forest", "grassland", "wetland"],
    cost: { rodent: 2 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 124,
    powers: [
      {
        id: "redTailedHawk.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  redWingedBlackbird: {
    id: "redWingedBlackbird",
    name: "Tordo Sargento",
    scientificName: "Agelaius phoeniceus",
    habitats: ["grassland", "wetland"],
    cost: { seed: 1 },
    points: 2,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 33,
    powers: [
      {
        id: "redWingedBlackbird.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  ringBilledGull: {
    id: "ringBilledGull",
    name: "Gaviota Piquianillada",
    scientificName: "Larus delawarensis",
    habitats: ["wetland"],
    cost: { wild: 2 },
    points: 4,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 122,
    powers: [
      {
        id: "ringBilledGull.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  roseBreastedGrosbeak: {
    id: "roseBreastedGrosbeak",
    name: "Picogrueso Pechirrosado",
    scientificName: "Pheucticus ludovicianus",
    habitats: ["forest"],
    cost: { insect: 1, seed: 1, fruit: 1 },
    points: 6,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 33,
    powers: [
      {
        id: "roseBreastedGrosbeak.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "seed",
        resourceAlt: "fruit",
        amount: 1,
        from: "feeder",
      },
    ],
  },
  roseateSpoonbill: {
    id: "roseateSpoonbill",
    name: "Espátula Rosada",
    scientificName: "Platalea ajaja",
    habitats: ["wetland"],
    cost: { insect: 1, seed: 1, fish: 1 },
    points: 6,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 127,
    powers: [
      {
        id: "roseateSpoonbill.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  rubyCrownedKinglet: {
    id: "rubyCrownedKinglet",
    name: "Reyezuelo de Moño Rubí",
    scientificName: "Regulus calendula",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 2,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 20,
    powers: [
      {
        id: "rubyCrownedKinglet.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["forest"],
      },
    ],
  },
  rubyThroatedHummingbird: {
    id: "rubyThroatedHummingbird",
    name: "Colibrí Gorgirrubí",
    scientificName: "Archilochus colubris",
    habitats: ["forest", "grassland", "wetland"],
    cost: { wild: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 10,
    powers: [
      {
        id: "rubyThroatedHummingbird.power1",
        timing: "onActivate",
        kind: "allPlayersGainDie",
      },
    ],
  },
  ruddyDuck: {
    id: "ruddyDuck",
    name: "Pato Tepalcate",
    scientificName: "Oxyura jamaicensis",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 0,
    eggCapacity: 5,
    nestType: "platform",
    wingspanCm: 48,
    powers: [
      {
        id: "ruddyDuck.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        thenDiscard: true,
      },
    ],
  },
  sandhillCrane: {
    id: "sandhillCrane",
    name: "Grulla Canadiense",
    scientificName: "Antigone canadensis",
    habitats: ["grassland", "wetland"],
    cost: { seed: 2, wild: 1 },
    points: 5,
    eggCapacity: 1,
    nestType: "ground",
    wingspanCm: 196,
    powers: [
      {
        id: "sandhillCrane.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 2,
        source: "deck",
        costResource: "seed",
        costAmount: 1,
      },
    ],
  },
  savannahSparrow: {
    id: "savannahSparrow",
    name: "Gorrión Sabanero",
    scientificName: "Passerculus sandwichensis",
    habitats: ["grassland"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 18,
    powers: [
      {
        id: "savannahSparrow.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["grassland"],
      },
    ],
  },
  saysPhoebe: {
    id: "saysPhoebe",
    name: "Mosquero Llanero",
    scientificName: "Sayornis saya",
    habitats: ["grassland"],
    cost: { insect: 3 },
    points: 5,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 33,
    powers: [
      {
        id: "saysPhoebe.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "eachNestType",
        nestType: "bowl",
      },
    ],
  },
  scissorTailedFlycatcher: {
    id: "scissorTailedFlycatcher",
    name: "Tirano Tijereta",
    scientificName: "Tyrannus forficatus",
    habitats: ["grassland"],
    cost: { insect: 2, fruit: 1 },
    points: 8,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 38,
    powers: [
      {
        id: "scissorTailedFlycatcher.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "insect",
        benefitType: "resource",
      },
    ],
  },
  snowyEgret: {
    id: "snowyEgret",
    name: "Garceta Nívea",
    scientificName: "Egretta thula",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 4,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 104,
    powers: [
      {
        id: "snowyEgret.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  songSparrow: {
    id: "songSparrow",
    name: "Gorrión Cantor",
    scientificName: "Melospiza melodia",
    habitats: ["forest", "grassland", "wetland"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 0,
    eggCapacity: 5,
    nestType: "bowl",
    wingspanCm: 20,
    powers: [
      {
        id: "songSparrow.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  spottedOwl: {
    id: "spottedOwl",
    name: "Búho Manchado",
    scientificName: "Strix occidentalis",
    habitats: ["forest"],
    cost: { rodent: 2 },
    points: 5,
    eggCapacity: 1,
    nestType: "cavity",
    wingspanCm: 102,
    powers: [
      {
        id: "spottedOwl.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  spottedSandpiper: {
    id: "spottedSandpiper",
    name: "Playero Alzacolita",
    scientificName: "Actitis macularius",
    habitats: ["wetland"],
    cost: { insect: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 38,
    powers: [
      {
        id: "spottedSandpiper.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        benefitType: "card",
      },
    ],
  },
  spottedTowhee: {
    id: "spottedTowhee",
    name: "Toquí Manchado",
    scientificName: "Pipilo maculatus",
    habitats: ["forest", "grassland"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 0,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 28,
    powers: [
      {
        id: "spottedTowhee.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "seed",
        amount: 1,
      },
    ],
  },
  spraguesPipit: {
    id: "spraguesPipit",
    name: "Bisbita de Sprague",
    scientificName: "Anthus spragueii",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 25,
    powers: [
      {
        id: "spraguesPipit.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  stellersJay: {
    id: "stellersJay",
    name: "Chara Crestada",
    scientificName: "Cyanocitta stelleri",
    habitats: ["forest"],
    cost: { seed: 2, wild: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 48,
    powers: [
      {
        id: "stellersJay.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "feeder",
      },
    ],
  },
  swainsonsHawk: {
    id: "swainsonsHawk",
    name: "Aguililla de Swainson",
    scientificName: "Buteo swainsoni",
    habitats: ["grassland"],
    cost: { insect: 1, rodent: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 130,
    powers: [
      {
        id: "swainsonsHawk.power1",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 75,
      },
    ],
  },
  treeSwallow: {
    id: "treeSwallow",
    name: "Golondrina Bicolor",
    scientificName: "Tachycineta bicolor",
    habitats: ["wetland"],
    cost: { insect: 1, fruit: 1 },
    points: 3,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 38,
    powers: [
      {
        id: "treeSwallow.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  trumpeterSwan: {
    id: "trumpeterSwan",
    name: "Cisne Trompetero",
    scientificName: "Cygnus buccinator",
    habitats: ["wetland"],
    cost: { seed: 2, wild: 1 },
    points: 9,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 203,
    powers: [],
  },
  tuftedTitmouse: {
    id: "tuftedTitmouse",
    name: "Carbonero Copetón",
    scientificName: "Baeolophus bicolor",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 25,
    powers: [
      {
        id: "tuftedTitmouse.power1",
        timing: "onActivate",
        kind: "playSecondBird",
        habitats: ["forest"],
      },
    ],
  },
  turkeyVulture: {
    id: "turkeyVulture",
    name: "Zopilote Aura",
    scientificName: "Cathartes aura",
    habitats: ["forest", "grassland", "wetland"],
    cost: {},
    points: 1,
    eggCapacity: 1,
    nestType: "cavity",
    wingspanCm: 170,
    powers: [
      {
        id: "turkeyVulture.power1",
        timing: "onceBetweenTurns",
        kind: "gainResource",
        amount: 1,
        from: "feeder",
        anyDie: true,
      },
    ],
  },
  violetGreenSwallow: {
    id: "violetGreenSwallow",
    name: "Golondrina Verdemar",
    scientificName: "Tachycineta thalassina",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 2 },
    points: 3,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 36,
    powers: [
      {
        id: "violetGreenSwallow.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  westernMeadowlark: {
    id: "westernMeadowlark",
    name: "Pradero Occidental",
    scientificName: "Sturnella neglecta",
    habitats: ["grassland"],
    cost: { insect: 1, seed: 1 },
    points: 2,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 38,
    powers: [
      {
        id: "westernMeadowlark.power1",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "allPlayersNestType",
        nestType: "ground",
        activePlayerBonus: 1,
      },
    ],
  },
  westernTanager: {
    id: "westernTanager",
    name: "Tángara Occidental",
    scientificName: "Piranga ludoviciana",
    habitats: ["forest"],
    cost: { insect: 2, fruit: 1 },
    points: 6,
    eggCapacity: 2,
    nestType: "bowl",
    wingspanCm: 30,
    powers: [
      {
        id: "westernTanager.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        resourceAlt: "fruit",
        amount: 1,
        from: "feeder",
      },
    ],
  },
  whiteBreastedNuthatch: {
    id: "whiteBreastedNuthatch",
    name: "Sita Pechiblanca",
    scientificName: "Sitta carolinensis",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed"],
    points: 2,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 28,
    powers: [
      {
        id: "whiteBreastedNuthatch.power1",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  whiteCrownedSparrow: {
    id: "whiteCrownedSparrow",
    name: "Gorrión Coroniblanco",
    scientificName: "Zonotrichia luecophrys",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, seed: 1 },
    points: 2,
    eggCapacity: 5,
    nestType: "ground",
    wingspanCm: 25,
    powers: [
      {
        id: "whiteCrownedSparrow.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  whiteFacedIbis: {
    id: "whiteFacedIbis",
    name: "Ibis Ojirrojo",
    scientificName: "Plegadis chihi",
    habitats: ["wetland"],
    cost: { insect: 2, fish: 1 },
    points: 8,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 91,
    powers: [
      {
        id: "whiteFacedIbis.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  whoopingCrane: {
    id: "whoopingCrane",
    name: "Grulla Trompetera",
    scientificName: "Grus americana",
    habitats: ["wetland"],
    cost: { wild: 3 },
    points: 6,
    eggCapacity: 1,
    nestType: "ground",
    wingspanCm: 221,
    powers: [
      {
        id: "whoopingCrane.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  wildTurkey: {
    id: "wildTurkey",
    name: "Guajolote Silvestre",
    scientificName: "Meleagris gallopavo",
    habitats: ["forest", "grassland"],
    cost: { seed: 2, fruit: 1 },
    points: 8,
    eggCapacity: 5,
    nestType: "ground",
    wingspanCm: 135,
    powers: [],
  },
  willet: {
    id: "willet",
    name: "Playero Pihuiuí",
    scientificName: "Tringa semipalmata",
    habitats: ["wetland"],
    cost: {},
    costAnyOf: ["insect", "fish"],
    points: 4,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 66,
    powers: [
      {
        id: "willet.power1",
        timing: "onActivate",
        kind: "diceHuntPredator",
        resource: "fish",
      },
    ],
  },
  wilsonsSnipe: {
    id: "wilsonsSnipe",
    name: "Agachona de Wilson",
    scientificName: "Gallinago delicata",
    habitats: ["wetland"],
    cost: { insect: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "ground",
    wingspanCm: 41,
    powers: [
      {
        id: "wilsonsSnipe.power1",
        timing: "onActivate",
        kind: "allPlayersGain",
        benefitType: "card",
      },
    ],
  },
  woodDuck: {
    id: "woodDuck",
    name: "Pato Arcoíris",
    scientificName: "Aix sponsa",
    habitats: ["forest", "wetland"],
    cost: { seed: 2, fruit: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 76,
    powers: [
      {
        id: "woodDuck.power1",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        thenDiscard: true,
      },
    ],
  },
  woodStork: {
    id: "woodStork",
    name: "Cigüeña Americana",
    scientificName: "Mycteria americana",
    habitats: ["wetland"],
    cost: { fish: 1, rodent: 1, wild: 1 },
    points: 6,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 155,
    powers: [
      {
        id: "woodStork.power1",
        timing: "onActivate",
        kind: "gainBonusCard",
        drawCount: 2,
        keepCount: 1,
      },
    ],
  },
  yellowBelliedSapsucker: {
    id: "yellowBelliedSapsucker",
    name: "Chupasavia Vientre Amarillo",
    scientificName: "Sphyrapicus varius",
    habitats: ["forest"],
    cost: { insect: 1, fruit: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 41,
    powers: [
      {
        id: "yellowBelliedSapsucker.power1",
        timing: "onActivate",
        kind: "gainResource",
        resource: "insect",
        amount: 1,
      },
    ],
  },
  yellowBilledCuckoo: {
    id: "yellowBilledCuckoo",
    name: "Cuclillo Piquigualdo",
    scientificName: "Coccyzus americanus",
    habitats: ["forest"],
    cost: { insect: 2, wild: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 46,
    powers: [
      {
        id: "yellowBilledCuckoo.power1",
        timing: "onceBetweenTurns",
        kind: "layEgg",
        amount: 1,
        target: "nestType",
        nestType: "bowl",
      },
    ],
  },
  yellowBreastedChat: {
    id: "yellowBreastedChat",
    name: "Buscabreña",
    scientificName: "Icteria virens",
    habitats: ["forest", "grassland", "wetland"],
    cost: { insect: 1, fruit: 2 },
    points: 5,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 25,
    powers: [
      {
        id: "yellowBreastedChat.power1",
        timing: "onActivate",
        kind: "moveToHabitat",
      },
    ],
  },
  yellowHeadedBlackbird: {
    id: "yellowHeadedBlackbird",
    name: "Tordo Cabeciamarillo",
    scientificName: "Xanthocephalus xanthocephalus",
    habitats: ["wetland"],
    cost: { insect: 1, seed: 1 },
    points: 4,
    eggCapacity: 3,
    nestType: "bowl",
    wingspanCm: 38,
    powers: [
      {
        id: "yellowHeadedBlackbird.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenGainEgg: true,
      },
    ],
  },
  yellowRumpedWarbler: {
    id: "yellowRumpedWarbler",
    name: "Chipe Coronado",
    scientificName: "Setophaga coronata",
    habitats: ["forest"],
    cost: {},
    costAnyOf: ["insect", "seed", "fruit"],
    points: 1,
    eggCapacity: 4,
    nestType: "bowl",
    wingspanCm: 23,
    powers: [
      {
        id: "yellowRumpedWarbler.power1",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
};

export const bonusCardsCatalog: Record<string, BonusCard> = {
  rodentExpert: {
    id: "rodentExpert",
    name: "Experto en Roedores",
    description: "Aves con coste de roedor en su dieta.",
    conditionType: "birdsWithFoodCost",
    resourceCost: "rodent",
    tiers: [
      { threshold: 2, points: 3 },
      { threshold: 4, points: 7 },
    ],
  },
  forestGuardian: {
    id: "forestGuardian",
    name: "Guardián de Bosques",
    description: "Aves que habitan en el bosque.",
    conditionType: "birdsInHabitat",
    habitat: "forest",
    tiers: [
      { threshold: 3, points: 4 },
      { threshold: 5, points: 8 },
    ],
  },
  wetlandEcologist: {
    id: "wetlandEcologist",
    name: "Ecólogo de Humedales",
    description: "Aves que habitan en el río/humedal.",
    conditionType: "birdsInHabitat",
    habitat: "wetland",
    tiers: [
      { threshold: 3, points: 4 },
      { threshold: 5, points: 8 },
    ],
  },
  nestBuilderCavity: {
    id: "nestBuilderCavity",
    name: "Arquitecto de Cavidades",
    description: "Aves con nido en cavidad.",
    conditionType: "birdsWithNest",
    nestType: "cavity",
    tiers: [
      { threshold: 2, points: 3 },
      { threshold: 4, points: 7 },
    ],
  },
  largeBroods: {
    id: "largeBroods",
    name: "Nidadas Grandes",
    description: "Huevos totales acumulados en tu tablero.",
    conditionType: "totalEggs",
    tiers: [
      { threshold: 6, points: 3 },
      { threshold: 10, points: 6 },
    ],
  },
};
