import type { BonusCard, SpeciesCard } from "./types";

export const speciesCards: Record<string, SpeciesCard> = {
  meadowSparrow: {
    id: "meadowSparrow",
    name: "Gorrión de Pradera",
    scientificName: "Passerculus sandwichensis",
    habitats: ["grassland"],
    cost: { seed: 1 },
    points: 2,
    eggCapacity: 4,
    nestType: "cup",
    wingspanCm: 20,
    powers: [
      {
        id: "meadowSparrow.grassland.draw",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
      },
    ],
  },
  riverHeron: {
    id: "riverHeron",
    name: "Garza de Río",
    scientificName: "Ardea herodias",
    habitats: ["wetland"],
    cost: { fish: 1, insect: 1 },
    points: 5,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 100,
    powers: [
      {
        id: "riverHeron.wetland.fish",
        timing: "onActivate",
        kind: "gainResource",
        resource: "fish",
        amount: 1,
      },
    ],
  },
  orchardFinch: {
    id: "orchardFinch",
    name: "Pinzón de Huerto",
    scientificName: "Haemorhous mexicanus",
    habitats: ["forest", "grassland"],
    cost: { fruit: 1 },
    points: 3,
    eggCapacity: 3,
    nestType: "cup",
    wingspanCm: 22,
    powers: [
      {
        id: "orchardFinch.play.egg",
        timing: "onPlay",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  marshWren: {
    id: "marshWren",
    name: "Ratona de Juncal",
    scientificName: "Cistothorus palustris",
    habitats: ["wetland"],
    cost: { insect: 1 },
    points: 1,
    eggCapacity: 5,
    nestType: "cavity",
    wingspanCm: 15,
    powers: [
      {
        id: "marshWren.wetland.filter",
        timing: "onActivate",
        kind: "drawCard",
        amount: 1,
        thenDiscard: true,
      },
    ],
  },
  cliffSwallow: {
    id: "cliffSwallow",
    name: "Golondrina de Acantilado",
    scientificName: "Petrochelidon pyrrhonota",
    habitats: ["grassland", "wetland"],
    cost: { insect: 1, seed: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "cup",
    wingspanCm: 28,
    powers: [
      {
        id: "cliffSwallow.grassland.egg",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  kelpGull: {
    id: "kelpGull",
    name: "Gaviota de Algas",
    scientificName: "Larus dominicanus",
    habitats: ["wetland"],
    cost: { fish: 1 },
    points: 2,
    eggCapacity: 3,
    nestType: "ground",
    wingspanCm: 120,
    powers: [
      {
        id: "kelpGull.wetland.tuck",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "hand",
        thenDraw: true,
      },
    ],
  },
  acornJay: {
    id: "acornJay",
    name: "Arrendajo Bellotero",
    scientificName: "Melanerpes formicivorus",
    habitats: ["forest"],
    cost: { seed: 1, fruit: 1 },
    points: 4,
    eggCapacity: 2,
    nestType: "cavity",
    wingspanCm: 35,
    powers: [
      {
        id: "acornJay.forest.seed",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  reedWarbler: {
    id: "reedWarbler",
    name: "Carricero de Cañaveral",
    scientificName: "Acrocephalus scirpaceus",
    habitats: ["wetland"],
    cost: { insect: 2 },
    points: 3,
    eggCapacity: 5,
    nestType: "cup",
    wingspanCm: 19,
    powers: [
      {
        id: "reedWarbler.play.draw",
        timing: "onPlay",
        kind: "drawCard",
        amount: 1,
      },
    ],
  },
  pineGrosbeak: {
    id: "pineGrosbeak",
    name: "Picogrueso de Pinar",
    scientificName: "Pinicola enucleator",
    habitats: ["forest"],
    cost: { fruit: 2 },
    points: 5,
    eggCapacity: 3,
    nestType: "cup",
    wingspanCm: 30,
    powers: [
      {
        id: "pineGrosbeak.forest.fruit",
        timing: "onActivate",
        kind: "gainResource",
        resource: "fruit",
        amount: 1,
      },
    ],
  },
  tidePlover: {
    id: "tidePlover",
    name: "Chorlito de Marea",
    scientificName: "Charadrius semipalmatus",
    habitats: ["wetland"],
    cost: { fish: 1, seed: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "ground",
    wingspanCm: 40,
    powers: [
      {
        id: "tidePlover.wetland.egg",
        timing: "onActivate",
        kind: "layEgg",
        amount: 1,
        target: "self",
      },
    ],
  },
  redTailedHawk: {
    id: "redTailedHawk",
    name: "Aguilucho Colirrojo",
    scientificName: "Buteo jamaicensis",
    habitats: ["forest", "grassland"],
    cost: { rodent: 2 },
    points: 7,
    eggCapacity: 2,
    nestType: "platform",
    wingspanCm: 125,
    powers: [
      {
        id: "redTailedHawk.hunt",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 65,
      },
    ],
  },
  barnOwl: {
    id: "barnOwl",
    name: "Lechuza Común",
    scientificName: "Tyto alba",
    habitats: ["forest", "grassland"],
    cost: { rodent: 1, wild: 1 },
    points: 6,
    eggCapacity: 3,
    nestType: "cavity",
    wingspanCm: 110,
    powers: [
      {
        id: "barnOwl.hunt",
        timing: "onActivate",
        kind: "huntPredator",
        maxWingspanCm: 50,
      },
    ],
  },
  americanRobin: {
    id: "americanRobin",
    name: "Mirlo Primavera",
    scientificName: "Turdus migratorius",
    habitats: ["forest", "grassland"],
    cost: { insect: 1, fruit: 1 },
    points: 3,
    eggCapacity: 4,
    nestType: "cup",
    wingspanCm: 38,
    powers: [
      {
        id: "americanRobin.allGain",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "insect",
      },
    ],
  },
  woodDuck: {
    id: "woodDuck",
    name: "Pato Joyuyo",
    scientificName: "Aix sponsa",
    habitats: ["forest", "wetland"],
    cost: { seed: 1, insect: 1 },
    points: 4,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 75,
    powers: [
      {
        id: "woodDuck.drawFilter",
        timing: "onActivate",
        kind: "drawCard",
        amount: 2,
        thenDiscard: true,
      },
    ],
  },
  tuftedTitmouse: {
    id: "tuftedTitmouse",
    name: "Herrerillo Bicolor",
    scientificName: "Baeolophus bicolor",
    habitats: ["forest"],
    cost: { seed: 1 },
    points: 2,
    eggCapacity: 4,
    nestType: "cavity",
    wingspanCm: 24,
    powers: [
      {
        id: "tuftedTitmouse.cache",
        timing: "onActivate",
        kind: "cacheFood",
        resource: "seed",
        amount: 1,
        source: "supply",
      },
    ],
  },
  mallard: {
    id: "mallard",
    name: "Ánade Real",
    scientificName: "Anas platyrhynchos",
    habitats: ["wetland"],
    cost: { seed: 1, insect: 1 },
    points: 3,
    eggCapacity: 5,
    nestType: "ground",
    wingspanCm: 90,
    powers: [
      {
        id: "mallard.tuckDeck",
        timing: "onActivate",
        kind: "tuckCard",
        amount: 1,
        source: "deck",
        thenDraw: false,
      },
    ],
  },
  rubyThroatedHummingbird: {
    id: "rubyThroatedHummingbird",
    name: "Colibrí Gorgirrubí",
    scientificName: "Archilochus colubris",
    habitats: ["forest", "grassland", "wetland"],
    cost: { fruit: 1 },
    points: 2,
    eggCapacity: 2,
    nestType: "cup",
    wingspanCm: 10,
    powers: [
      {
        id: "rubyThroatedHummingbird.allGainFruit",
        timing: "onActivate",
        kind: "allPlayersGain",
        resource: "fruit",
      },
    ],
  },
};

export const bonusCardsCatalog: Record<string, BonusCard> = {
  rodentExpert: {
    id: "rodentExpert",
    name: "Experto en Roedores",
    description: "Aves con coste de roedor en su dieta.",
    conditionType: "birdsWithFoodCost",
    resourceCost: "rodent",
    tiers: [
      { threshold: 2, points: 3 },
      { threshold: 4, points: 7 },
    ],
  },
  forestGuardian: {
    id: "forestGuardian",
    name: "Guardián de Bosques",
    description: "Aves que habitan en el bosque.",
    conditionType: "birdsInHabitat",
    habitat: "forest",
    tiers: [
      { threshold: 3, points: 4 },
      { threshold: 5, points: 8 },
    ],
  },
  wetlandEcologist: {
    id: "wetlandEcologist",
    name: "Ecólogo de Humedales",
    description: "Aves que habitan en el río/humedal.",
    conditionType: "birdsInHabitat",
    habitat: "wetland",
    tiers: [
      { threshold: 3, points: 4 },
      { threshold: 5, points: 8 },
    ],
  },
  nestBuilderCavity: {
    id: "nestBuilderCavity",
    name: "Arquitecto de Cavidades",
    description: "Aves con nido en cavidad.",
    conditionType: "birdsWithNest",
    nestType: "cavity",
    tiers: [
      { threshold: 2, points: 3 },
      { threshold: 4, points: 7 },
    ],
  },
  largeBroods: {
    id: "largeBroods",
    name: "Nidadas Grandes",
    description: "Huevos totales acumulados en tu tablero.",
    conditionType: "totalEggs",
    tiers: [
      { threshold: 6, points: 3 },
      { threshold: 10, points: 6 },
    ],
  },
};
